from collections.abc import Callable
from dataclasses import dataclass
from typing import Any
from urllib.parse import quote


REPORT_TITLE = "Spica Advisor report"
SEVERITIES = ("high", "medium", "low")
SEVERITY_LABELS = {"high": "🔴 High", "medium": "🟠 Medium", "low": "🟡 Low"}
# GitHub honours "\|" even inside code spans, unlike other escapes, so table cells escape only what breaks them.
CELL_ESCAPES = str.maketrans({"|": "\\|", "\r": " ", "\n": " "})
LINK_LABEL_ESCAPES = str.maketrans({"[": "\\[", "]": "\\]"})
FAILED_SECTION = "⚠️ This investigation failed, so its findings are missing. See the workflow logs."
DISCLAIMER = "<sub>Findings are generated by an LLM and can be wrong. Review each one before acting on it.</sub>"


def escape(text):
    return str(text).translate(CELL_ESCAPES)


def code(text):
    return f"`{str(text).replace('`', '')}`"


@dataclass(frozen=True)
class Links:
    source_url: str | None = None

    def resource(self, name, path):
        label = escape(name or path or "unknown").translate(LINK_LABEL_ESCAPES)
        if not path:
            return label
        if self.source_url:
            return f"[{label}]({self.source_url}/{quote(path)})"
        return f"{label} ({code(path)})"


@dataclass(frozen=True)
class Row:
    severity: str
    cells: tuple[str, ...]


@dataclass(frozen=True)
class Section:
    title: str
    description: str
    columns: tuple[str, ...]
    rows: Callable[[Any, Links], list[Row]]
    appendix: Callable[[Any, Links], str] | None = None


@dataclass(frozen=True)
class ReportMetadata:
    model: str
    commit: str | None = None
    commit_url: str | None = None
    run_url: str | None = None
    source_url: str | None = None


@dataclass(frozen=True)
class MarkdownReport:
    text: str
    finding_count: int
    complete: bool


def table(columns, rows):
    return "\n".join(
        "| " + " | ".join(cells) + " |"
        for cells in (columns, ["---"] * len(columns), *rows)
    )


def header(metadata):
    details = [f"Model {code(metadata.model)}"]
    if metadata.commit:
        commit = code(metadata.commit[:7])
        details.insert(0, f"Commit [{commit}]({metadata.commit_url})" if metadata.commit_url else f"Commit {commit}")
    if metadata.run_url:
        details.append(f"[Workflow run]({metadata.run_url})")
    return f"## {REPORT_TITLE}\n\n" + " · ".join(details)


def overview(results):
    counts = [
        [section.title, "⚠️ Failed", "–", "–"] if rows is None
        else [section.title, *(str(sum(row.severity == severity for row in rows)) for severity in SEVERITIES)]
        for section, rows in results
    ]
    summary = table(["Investigation", *SEVERITY_LABELS.values()], counts)
    if all(rows == [] for _, rows in results):
        return "✅ No findings.\n\n" + summary
    return summary


def render_section(section, rows, appendix=""):
    if rows is None:
        body = FAILED_SECTION
    elif not rows:
        body = "No findings."
    else:
        body = table(["Severity", *section.columns], [[SEVERITY_LABELS[row.severity], *row.cells] for row in rows])
    return "\n\n".join(part for part in (f"### {section.title}", section.description, body, appendix) if part)


def sorted_rows(rows):
    return sorted(rows, key=lambda row: SEVERITIES.index(row.severity))


def render_report(reports, metadata):
    links = Links(metadata.source_url)
    results = [
        (section, None if report is None else sorted_rows(section.rows(report, links)))
        for section, report in reports
    ]
    appendices = [
        section.appendix(report, links) if section.appendix and rows else ""
        for (section, report), (_, rows) in zip(reports, results)
    ]
    text = "\n\n".join([
        header(metadata),
        overview(results),
        *(render_section(section, rows, appendix) for (section, rows), appendix in zip(results, appendices)),
        DISCLAIMER,
    ]) + "\n"
    return MarkdownReport(
        text=text,
        finding_count=sum(len(rows) for _, rows in results if rows),
        complete=all(rows is not None for _, rows in results),
    )
