_id: syn2-fn-storage
name: Storage-Api
language: javascript
timeout: 60
triggers:
  uploadAvatar:
    type: http
    active: true
    options:
      method: Post
      path: /avatars
      preflight: true
      authorize: false
  removeAvatar:
    type: http
    active: true
    options:
      method: Delete
      path: /avatars
      preflight: true
      authorize: false
