_id: syn2-fn-pricing
name: Pricing-Api
language: javascript
timeout: 60
triggers:
  quote:
    type: http
    active: true
    options:
      method: Post
      path: /pricing/quote
      preflight: true
      authorize: false
  validateCoupon:
    type: http
    active: true
    options:
      method: Get
      path: /pricing/coupon
      preflight: true
      authorize: false
  ping:
    type: http
    active: true
    options:
      method: Get
      path: /pricing/ping
      preflight: true
      authorize: false
